### ISSUE TITLE
Non-deterministic training when --seed is provided

### ISSUE THREAD

**Issue by cgr71ii** [bitextor/bicleaner#72]
Hi!

I've trained 2 Bicleaner models using the same data and configuration, but the resulted models are different. The command I've used is:
```bash
paste <(zcat /home/docker/volume/data/parallel-corpus/DGT/DGT.clipped.en-fr.en.gz) <(zcat /home/docker/volume/data/parallel-corpus/DGT/DGT.clipped.en-fr.fr.gz) > /home/docker/volume/transient/50/bicleaner_train/training_parallel_corpus.en_fr

bicleaner-train /home/docker/volume/transient/50/bicleaner_train/training_parallel_corpus.en_fr -S /usr/local/lib/python3.8/dist-packages/bitextor/data/moses/tokenizer/tokenizer.perl -q -b -a -l en -T /usr/local/lib/python3.8/dist-packages/bitextor/data/moses/tokenizer/tokenizer.perl -q -b -a -l fr --treat_oovs --normalize_by_length -s en -t fr -d /home/docker/volume/permanent/50-generated-en-fr.dic.lex.e2f.gz -D /home/docker/volume/permanent/50-generated-en-fr.dic.lex.f2e.gz -f /home/docker/volume/transient/50/tempgizamodel.en-fr/corpus.en.filtered.vcb.gz -F /home/docker/volume/transient/50/tempgizamodel.en-fr/corpus.fr.filtered.vcb.gz -c /home/docker/volume/data/bicleaner-models/50/en-fr.classifier -m /home/docker/volume/data/bicleaner-models/50/generated-en-fr.yaml --classifier_type random_forest --seed 71213
```

The training data is https://object.pouta.csc.fi/OPUS-DGT/v2019/moses/en-fr.txt.zip, and for generating the dictionary statistical information https://object.pouta.csc.fi/OPUS-Europarl/v8/moses/en-fr.txt.zip has been used. The clipped version of both datasets has been generated taking the last 100000 sentences (i.e. `tail -n 100000`). Further details about how I generated the models can be checked out [here](https://github.com/bitextor/bitextor/blob/00bd9fec969bfdc4619e5466ddc047ecff181645/tests/run-tests.sh) (tests 40 and 50 are the ones that trains a model).

Full content of one of the generated YAML:
```yaml
classifier: /home/docker/volume/data/bicleaner-models/50/en-fr.classifier
classifier_type: random_forest
source_lang: en
target_lang: fr
source_dictionary: /home/docker/volume/permanent/50-generated-en-fr.dic.lex.e2f.gz
target_dictionary: /home/docker/volume/permanent/50-generated-en-fr.dic.lex.f2e.gz
source_word_freqs: /home/docker/volume/transient/50/tempgizamodel.en-fr/corpus.en.filtered.vcb.gz
target_word_freqs: /home/docker/volume/transient/50/tempgizamodel.en-fr/corpus.fr.filtered.vcb.gz
normalize_by_length: True
treat_oovs: True
qmax_limit: 40
disable_features_quest: True
good_test_histogram: [5, 43, 180, 377, 677, 850, 1003, 1155, 547, 163]
wrong_test_histogram: [869, 916, 1013, 917, 606, 383, 223, 63, 8, 0]
precision_histogram: [0.5001000, 0.5474573, 0.6064911, 0.6844521, 0.7740402, 0.8459613, 0.9070209, 0.9633264, 0.9888579, 1.0000000]
recall_histogram: [1.0000000, 0.9990000, 0.9904000, 0.9544000, 0.8790000, 0.7436000, 0.5736000, 0.3730000, 0.1420000, 0.0326000]
accuracy_histogram: [0.5001000, 0.5865173, 0.6738348, 0.7571514, 0.8111622, 0.8040608, 0.7573515, 0.6793359, 0.5701140, 0.5162032]
length_ratio: 0.8728353
features_version: 4
disable_lang_ident: False
source_tokenizer_command: /usr/local/lib/python3.8/dist-packages/bitextor/data/moses/tokenizer/tokenizer.perl -q -b -a -l en
target_tokenizer_command: /usr/local/lib/python3.8/dist-packages/bitextor/data/moses/tokenizer/tokenizer.perl -q -b -a -l fr
```

Diff of the two generated YAML files:
```
13,17c13,17
< good_test_histogram: [5, 43, 180, 377, 677, 850, 1003, 1155, 547, 163]
< wrong_test_histogram: [869, 916, 1013, 917, 606, 383, 223, 63, 8, 0]
< precision_histogram: [0.5001000, 0.5474573, 0.6064911, 0.6844521, 0.7740402, 0.8459613, 0.9070209, 0.9633264, 0.9888579, 1.0000000]
< recall_histogram: [1.0000000, 0.9990000, 0.9904000, 0.9544000, 0.8790000, 0.7436000, 0.5736000, 0.3730000, 0.1420000, 0.0326000]
< accuracy_histogram: [0.5001000, 0.5865173, 0.6738348, 0.7571514, 0.8111622, 0.8040608, 0.7573515, 0.6793359, 0.5701140, 0.5162032]
---
> good_test_histogram: [6, 42, 176, 401, 665, 897, 1026, 1080, 555, 152]
> wrong_test_histogram: [811, 886, 1065, 923, 648, 389, 214, 49, 13, 0]
> precision_histogram: [0.5001000, 0.5439495, 0.6000242, 0.6811181, 0.7691632, 0.8480000, 0.9106507, 0.9664684, 0.9819444, 1.0000000]
> recall_histogram: [1.0000000, 0.9988000, 0.9904000, 0.9552000, 0.8750000, 0.7420000, 0.5626000, 0.3574000, 0.1414000, 0.0304000]
> accuracy_histogram: [0.5001000, 0.5806161, 0.6650330, 0.7539508, 0.8061612, 0.8044609, 0.7536507, 0.6724345, 0.5693139, 0.5151030]
```

Integrity values of the generated classifiers (MD5) are different: db2ee88c2778e18aa5de61f7a7c92854 and 46b79715e9a02a7f85df25710e96323a

I think I posted all necessary information for further investigation or reproducibility. If anything else is needed, I'll provide the requested information/data.

PS: am I right guessing that `--seed` should generate the same model if the same configuration and data is provided? I don't know if the purpose of this flag is used for something else regarding reproducibility (maybe partial and not full reproducibility?).
